disable_existing_loggers: false
formatters:
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    level: INFO
    stream: ext://sys.stdout
  error_file:
    backupCount: 5
    class: logging.handlers.RotatingFileHandler
    filename: /var/log/fashion_api_errors.log
    formatter: json
    level: ERROR
    maxBytes: 10485760
  file:
    backupCount: 5
    class: logging.handlers.RotatingFileHandler
    filename: /var/log/fashion_api.log
    formatter: json
    level: INFO
    maxBytes: 10485760
loggers:
  fashion_api:
    handlers:
    - console
    - file
    - error_file
    level: INFO
    propagate: false
  uvicorn:
    handlers:
    - console
    level: INFO
    propagate: false
root:
  handlers:
  - console
  level: INFO
version: 1
